"""
vertex_agent.py — Gemini 2.5 Pro via Vertex AI, OpenAI-Python v1

* Auto-discovers XFLRpy tools and exposes them as function calls.
* Auth via service-account JSON (GOOGLE_APPLICATION_CREDENTIALS) or a
  one-shot VERTEX_ACCESS_TOKEN.
"""

from __future__ import annotations

import inspect
import json
import os
import sys
import logging
from typing import Any, Dict, Union, Optional, List, get_args, get_origin

from openai import OpenAI
from pydantic import create_model

# ── Google auth (only needed if we have to mint a token) ──
import google.auth
import google.auth.transport.requests
from google.oauth2.service_account import Credentials as SACreds

from dotenv import load_dotenv
load_dotenv(dotenv_path=".env")     # loads the .env file into os.environ

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('agent_debug.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


# ╭──────────────────────────────────────────────────────────╮
# │  BEARER-TOKEN HELPER                                     │
# ╰──────────────────────────────────────────────────────────╯
def _get_bearer_token() -> str:
    # 1) Prefer an already-minted bearer token if user exported one
    if (tok := os.getenv("VERTEX_ACCESS_TOKEN")):
        return tok

    # 2) Explicitly load the service-account JSON and request an access-token
    json_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if not json_path:
        raise RuntimeError("Neither VERTEX_ACCESS_TOKEN nor GOOGLE_APPLICATION_CREDENTIALS set")

    sa_creds = SACreds.from_service_account_file(
        json_path,
        scopes=["https://www.googleapis.com/auth/cloud-platform"],
    )
    sa_creds.refresh(google.auth.transport.requests.Request())
    return sa_creds.token              # <-- this is a ya29.<long-string> access token


# ╭──────────────────────────────────────────────────────────╮
# │  TOOL DISCOVERY UTILITIES                                │
# ╰──────────────────────────────────────────────────────────╯
TOOLS: list[Dict[str, Any]] = []
CALLBACKS: Dict[str, Any] = {}


def _serialize(obj: Any) -> Any:
    """Recursively JSON-serialise complex objects."""
    try:
        if hasattr(obj, "__dict__"):
            return {k: _serialize(v) for k, v in obj.__dict__.items() if not k.startswith("_")}
        if isinstance(obj, (list, tuple)):
            return [_serialize(i) for i in obj]
        if isinstance(obj, dict):
            return {k: _serialize(v) for k, v in obj.items()}
        if hasattr(obj, "isoformat"):
            return obj.isoformat()
        return obj
    except Exception as e:
        logger.error(f"❌ Serialization failed for {type(obj).__name__}: {e}")
        return f"<SerializationError: {str(e)}>"


def _build_schema(fn):
    try:
        sig = inspect.signature(fn)
        fields: Dict[str, tuple[Any, Any]] = {}
        for name, param in sig.parameters.items():
            if name == "self":
                continue
            ann = param.annotation if param.annotation is not inspect._empty else Any
            default = param.default if param.default is not inspect._empty else ...
            fields[name] = (ann, default)
        
        Model = create_model(f"{fn.__name__}Schema", **fields)
        Model.model_rebuild()
        
        schema = {
            "type": "function",
            "function": {
                "name": fn.__name__,
                "description": fn.__doc__ or f"{fn.__name__} autogenerated tool",
                "parameters": Model.model_json_schema(),
            },
        }
        return schema
    except Exception as e:
        logger.error(f"❌ Failed to build schema for {fn.__name__}: {e}")
        raise


def _setup_tools(tm):
    global TOOLS, CALLBACKS
    TOOLS, CALLBACKS = [], {}
    
    logger.info("🔧 Discovering tools...")
    
    for name, fn in inspect.getmembers(tm, predicate=inspect.ismethod):
        if not name.startswith("_"):
            try:
                schema = _build_schema(fn)
                TOOLS.append(schema)
                CALLBACKS[name] = fn
                logger.info(f"✅ {name}")
            except Exception as e:
                logger.error(f"❌ {name}: {e}")
    
    logger.info(f"🎯 Found {len(TOOLS)} tools: {list(CALLBACKS.keys())}")


# ╭──────────────────────────────────────────────────────────╮
# │  VERTEX  + OPENAI CLIENT                                 │
# ╰──────────────────────────────────────────────────────────╯
PROJECT_ID = os.getenv("VERTEX_PROJECT_ID")
if not PROJECT_ID:
    sys.exit("VERTEX_PROJECT_ID env var not set")

LOCATION = os.getenv("VERTEX_LOCATION", "us-central1")
MODEL_NAME = "google/gemini-2.5-pro"

BASE_URL = (
    f"https://{LOCATION}-aiplatform.googleapis.com/"
    f"v1/projects/{PROJECT_ID}/locations/{LOCATION}/endpoints/openapi"
)

client = OpenAI(api_key=_get_bearer_token(), base_url=BASE_URL)

# ╭──────────────────────────────────────────────────────────╮
# │  REPL LOOP                                              │
# ╰──────────────────────────────────────────────────────────╯
SYSTEM_PROMPT = (
    "You are **AeroGPT**, an expert aerodynamicist with direct access to XFLR5 "
    "via the provided tools. Think step-by-step, calling tools only when needed. "
    "Never invent plane names."
)

def _get_user_input(msgs: list[dict]):
    try:
        user = input("User > ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nBye")
        return 1

    if not user:
        return 1

    logger.info(f"👤 {user}")
    msgs.append({"role": "user", "content": user})
    return 0

def _make_api_call(msgs: list[dict]):
    try:
        rsp = client.chat.completions.create(
            model=MODEL_NAME,
            messages=msgs,
            tools=TOOLS,
            tool_choice="auto",
        )
        return rsp
    
    except Exception as e:
        logger.error(f"❌ API call failed: {e}")
        raise

def _handle_tool_calls(msg: dict, msgs: list[dict]):
    logger.info(f"🔧 {len(msg.tool_calls)} tool calls")
    
    for call in msg.tool_calls:
        logger.info(f"🛠️  {call.function.name}({call.function.arguments})")
        
        if call.function.name not in CALLBACKS:
            logger.error(f"❌ Tool '{call.function.name}' not found!")
            continue
        
        fn = CALLBACKS[call.function.name]
        
        try:
            args = json.loads(call.function.arguments or "{}")
            result = fn(**args)
            logger.info(f"✅ {call.function.name} -> {type(result).__name__}")
            
        except Exception as exc:
            logger.error(f"❌ {call.function.name} failed: {exc}")
            result = {"error": str(exc), "error_type": type(exc).__name__}

        try:
            serialized_result = _serialize(result)
            response_content = json.dumps(serialized_result)[:8000]
            
            tool_response = {
                "role": "tool",
                "tool_call_id": call.id,
                "name": call.function.name,
                "content": response_content,
            }
            
            logger.info(f"---------------- \n Appending tool response: \n {tool_response} \n ----------------")
            msgs.append(tool_response)
            
        except Exception as e:
            logger.error(f"❌ Serialization failed: {e}")
            fallback_response = {
                "role": "tool",
                "tool_call_id": call.id,
                "name": call.function.name,
                "content": json.dumps({"error": "Serialization failed", "details": str(e)})[:8000],
            }
            msgs.append(fallback_response)
            
def chat_loop(tm):
    _setup_tools(tm)
    msgs = [{"role": "system", "content": SYSTEM_PROMPT}]

    print("✈️  Vertex-Gemini 2.5 Pro REPL. CTRL-C to quit.")
    while True:
        input_result = _get_user_input(msgs)
        if input_result == 1:
            break

        # Make the API call
        rsp = _make_api_call(msgs)
        print("API call done >", rsp)

        msg = rsp.choices[0].message
        print("Gemini >", msg.content)

        msgs.append({"role": "assistant", "content": msg.content, "tool_calls": msg.tool_calls})

        # Handle tool calls if any
        if msg.tool_calls:
            print("Handling tool calls")
            _handle_tool_calls(msg, msgs)
            print("Tool calls handled")

            print("Making API call 2")
            rsp_2 = _make_api_call(msgs)
            msg_2 = rsp_2.choices[0].message
            print("Gemini >", msg_2.content)
            msgs.append({"role": "assistant", "content": msg_2.content})


# ╭──────────────────────────────────────────────────────────╮
# │  MAIN                                                   │
# ╰──────────────────────────────────────────────────────────╯
if __name__ == "__main__":
    from tools import ToolManager

    tm = ToolManager(
        project_path="xflrpy/projects/",
        project_name="test1.xfl",
        plane_name="baseline",
    )
    chat_loop(tm)
