"""
vertex_agent.py — Gemini 2.5 Pro via Vertex AI, OpenAI-Python v1

* Auto-discovers XFLRpy tools and exposes them as function calls.
* Auth via service-account JSON (GOOGLE_APPLICATION_CREDENTIALS) or a
  one-shot VERTEX_ACCESS_TOKEN.
"""

from __future__ import annotations

import inspect
import json
import os
import sys
from typing import Any, Dict, Union, Optional, List, get_args, get_origin

from openai import OpenAI
from pydantic import create_model

# ── Google auth (only needed if we have to mint a token) ──
import google.auth
import google.auth.transport.requests
from google.oauth2.service_account import Credentials as SACreds

from dotenv import load_dotenv
load_dotenv(dotenv_path=".env")     # loads the .env file into os.environ



# ╭──────────────────────────────────────────────────────────╮
# │  BEARER-TOKEN HELPER                                     │
# ╰──────────────────────────────────────────────────────────╯
def _get_bearer_token() -> str:
    # 1) Prefer an already-minted bearer token if user exported one
    if (tok := os.getenv("VERTEX_ACCESS_TOKEN")):
        return tok

    # 2) Explicitly load the service-account JSON and request an access-token
    json_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if not json_path:
        raise RuntimeError("Neither VERTEX_ACCESS_TOKEN nor GOOGLE_APPLICATION_CREDENTIALS set")

    sa_creds = SACreds.from_service_account_file(
        json_path,
        scopes=["https://www.googleapis.com/auth/cloud-platform"],
    )
    sa_creds.refresh(google.auth.transport.requests.Request())
    return sa_creds.token              # <-- this is a ya29.<long-string> access token


# ╭──────────────────────────────────────────────────────────╮
# │  TOOL DISCOVERY UTILITIES                                │
# ╰──────────────────────────────────────────────────────────╯
TOOLS: list[Dict[str, Any]] = []
CALLBACKS: Dict[str, Any] = {}


def _serialize(obj: Any) -> Any:
    """Recursively JSON-serialise complex objects."""
    if hasattr(obj, "__dict__"):
        return {k: _serialize(v) for k, v in obj.__dict__.items() if not k.startswith("_")}
    if isinstance(obj, (list, tuple)):
        return [_serialize(i) for i in obj]
    if isinstance(obj, dict):
        return {k: _serialize(v) for k, v in obj.items()}
    if hasattr(obj, "isoformat"):
        return obj.isoformat()
    return obj


def _build_schema(fn):
    sig = inspect.signature(fn)
    fields: Dict[str, tuple[Any, Any]] = {}
    for name, param in sig.parameters.items():
        if name == "self":
            continue
        ann = param.annotation if param.annotation is not inspect._empty else Any
        default = param.default if param.default is not inspect._empty else ...
        fields[name] = (ann, default)
    Model = create_model(f"{fn.__name__}Schema", **fields)
    Model.model_rebuild()
    return {
        "type": "function",
        "function": {
            "name": fn.__name__,
            "description": fn.__doc__ or f"{fn.__name__} autogenerated tool",
            "parameters": Model.model_json_schema(),
        },
    }


def _setup_tools(tm):
    global TOOLS, CALLBACKS
    TOOLS, CALLBACKS = [], {}
    for name, fn in inspect.getmembers(tm, predicate=inspect.ismethod):
        if not name.startswith("_"):
            schema = _build_schema(fn)
            TOOLS.append(schema)
            CALLBACKS[name] = fn


# ╭──────────────────────────────────────────────────────────╮
# │  VERTEX  + OPENAI CLIENT                                 │
# ╰──────────────────────────────────────────────────────────╯
PROJECT_ID = os.getenv("VERTEX_PROJECT_ID")
if not PROJECT_ID:
    sys.exit("VERTEX_PROJECT_ID env var not set")

LOCATION = os.getenv("VERTEX_LOCATION", "us-central1")
MODEL_NAME = "google/gemini-2.5-pro"

BASE_URL = (
    f"https://{LOCATION}-aiplatform.googleapis.com/"
    f"v1/projects/{PROJECT_ID}/locations/{LOCATION}/endpoints/openapi"
)

client = OpenAI(api_key=_get_bearer_token(), base_url=BASE_URL)

# ╭──────────────────────────────────────────────────────────╮
# │  REPL LOOP                                              │
# ╰──────────────────────────────────────────────────────────╯
SYSTEM_PROMPT = (
    "You are **AeroGPT**, an expert aerodynamicist with direct access to XFLR5 "
    "via the provided tools. Think step-by-step, calling tools only when needed. "
    "Never invent plane names."
)


def chat_loop(tm):
    _setup_tools(tm)
    msgs = [{"role": "system", "content": SYSTEM_PROMPT}]

    print("✈️  Vertex-Gemini 2.5 Pro REPL. CTRL-C to quit.")
    while True:
        try:
            user = input("User > ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nBye")
            break
        if not user:
            continue

        msgs.append({"role": "user", "content": user})

        # Make the API call
        rsp = client.chat.completions.create(
            model=MODEL_NAME,
            messages=msgs,
            tools=TOOLS,
            tool_choice="auto",
        )
        msg = rsp.choices[0].message

        # Handle tool calls if any
        if msg.tool_calls:
            for call in msg.tool_calls:
                fn = CALLBACKS[call.function.name]
                args = json.loads(call.function.arguments or "{}")
                try:
                    result = fn(**args)
                except Exception as exc:
                    result = {"error": str(exc), "error_type": type(exc).__name__}

                msgs.append(
                    {
                        "role": "tool",
                        "tool_call_id": call.id,
                        "name": call.function.name,
                        "content": json.dumps(_serialize(result))[:8000],
                    }
                )
            # Continue to next iteration to let Gemini process tool responses
            continue

        # Normal assistant reply
        print("Gemini >", msg.content)
        msgs.append({"role": "assistant", "content": msg.content})


# ╭──────────────────────────────────────────────────────────╮
# │  MAIN                                                   │
# ╰──────────────────────────────────────────────────────────╯
if __name__ == "__main__":
    from tools import ToolManager

    tm = ToolManager(
        project_path="xflrpy/projects/",
        project_name="test1.xfl",
        plane_name="baseline",
    )
    chat_loop(tm)
